config/routes.rb
Rails.application.routes.draw do

  get 'findjobs/indeed'

  get 'findjobs/pagination'
  get 'findjobs/download'
  
  root 'findjobs#pagination'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joblink.rb
class Joblink < ApplicationRecord
  scope :order_joblink, -> { order('id DESC') }

  def self.to_csv
    attributes = %w{company_name job_title job_href domain keyword}

    CSV.generate(headers: true) do |csv|
      csv << %w{企業名 求人名 求人詳細url サイト名 検索キーワード}

      all.reverse.each do |joblink|
        csv << attributes.map { |attr| joblink.send(attr) }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/findjobs_controller.rb
class FindjobsController < ApplicationController

  include FindjobHelper

  def indeed
    if params[:query].present?
      initialize_job
      if @joblink
        update_job
      else
        create_job
      end
    end
  end

  def pagination
    session[:keyword] ||= ''
    @joblinks = Joblink.where(keyword: session[:keyword])
                       .order_joblink
                       .page(params[:page])
                       .per(10)
  end

  def download
    @joblink = Joblink.where(keyword: session[:keyword])
    respond_to do |format|
      format.csv { send_data @joblink.to_csv,
                   filename: "#{session[:keyword]}.csv" }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/findjob_helper.rb
module FindjobHelper
  DOMAIN = 'https://jp.indeed.com/'
  PRE_URL = 'https://jp.indeed.com/求人?q='
  PAGE = '&start='
  PRE_JOB_HREF = 'https://jp.indeed.com'

  require 'rubygems'
  require 'mechanize'
  require 'csv'

  def initialize_job
    @init = Mechanize.new
    @keyword = params[:query].downcase
    session[:keyword] = @keyword if @keyword
    @joblink = Joblink.where(keyword: @keyword).first
    
    @page_index = 0

    @job_title_arr = []
    @job_href_arr = []
    @company_name_arr = []
    @location_arr = []
    @job_description_arr = []

    @keyword = params[:query]
    @domain = DOMAIN
  end

  def update_job
    while @page_index < 1100
      url = PRE_URL + @keyword + PAGE + @page_index.to_s
      page = @init.get url
      results = page.search('div.row.result')
      href_arr = Joblink.all.collect(&:job_href)
      if results.present?

        results.each do |result|
        href = PRE_JOB_HREF + result.search('h2 a').attribute('href').text.strip
          unless href_arr.include?(href) ||
            @job_href_arr.include?(href)
            
            insert_data_to_array(result)
          end
        end

      else
        next
      end

      @page_index += 10

    end

    insert_data_to_database

  end

  def create_job
    while @page_index < 1100
      url = PRE_URL + @keyword + PAGE + @page_index.to_s
      page = @init.get url
      results = page.search('div.row.result')
      
      if results.present?

        results.each do |result|
        href = PRE_JOB_HREF + result.search('h2 a').attribute('href').text.strip
          unless @job_href_arr.include?(href)
            insert_data_to_array(result)
          end

        end
      else
        next
      end

      @page_index += 10

    end

    insert_data_to_database

  end

  def insert_data_to_array(result)
    if result.search('h2 a')
      title = result.search('h2 a').text.strip
      href = PRE_JOB_HREF + result.search('h2 a').attribute('href').text.strip

      @job_title_arr << title
      @job_href_arr << href
    else
      @job_title_arr << ''
      @job_href_arr << ''
    end
    
    if result.search('span span')[0]
      company_name = result.search('span span')[0].text.strip

      @company_name_arr << company_name
    else
      @company_name_arr << ''
    end
    
    if result.search('span span')[2]
      location = result.search('span span')[2].text.strip

      @location_arr << location
    else
      @location_arr << ''
    end

    if result.search('table span')
      job_description = result.search('table span').text.strip
      @job_description_arr << job_description
    else
      @job_description_arr << ''
    end
  end

  def insert_data_to_database
    joblink_arr = []

    @job_title_arr.each_with_index do |job_title, index|
      @joblink = Joblink.new
      @joblink.domain = @domain
      @joblink.keyword = @keyword
      @joblink.job_title = job_title
      @joblink.job_href = @job_href_arr[index]
      @joblink.company_name = @company_name_arr[index]
      @joblink.location = @location_arr[index]
      @joblink.job_description = @job_description_arr[index]
      joblink_arr.unshift(@joblink)
    end

    Joblink.import joblink_arr
  end

end

app/views/findjobs/_content.html.erb
<% if session[:keyword].present? %>
    <%= link_to "DOWNLOAD-CSV", findjobs_download_path(format: :csv), class: "btn btn-primary" %>
    <br>
    <br>
    <div>
        <% if @joblinks %>
            <% @joblinks.each do |job| %>
                <a href=<%= job.job_href %> ><h2><%= job.job_title %></h2></a>
                <p><%= job.company_name %></p>   
                <p><%= job.location %></p>
                <p><%= job.job_description %></p>
            <% end %>
        <% else %>
            <div>
                <b> NO DATA TO DISPLAY!</b>
            </div>
        <% end %>
    </div>
    <div class="outer">
        <div class="inner">
            <%= paginate @joblinks %>
        </div>
    </div>
<% end %>

app/views/findjobs/indeed.js.erb
$("#job_query").val("");
window.location.replace("/");

app/views/findjobs/pagination.html.erb
<div class="row" style="margin-top: 50px;" >
  <div class="search" style="margin: auto !important;">
      <form action = "/findjobs/indeed" class="btn" data-remote = "true" id="form_key">
          <% if session[:keyword].length > 0 %>
            <input type="text" name = "query" id="job_query" class="form-control" placeholder=<%= session[:keyword] %> />
          <% else %>
            <input type="text" name = "query" id="job_query" class="form-control" placeholder="Search" />
          <% end %>
          <button type="submit" class="btn btn-primary" style="padding-bottom: 27px;">Search</button>
      </form>
  </div>
</div>

<div class="row">
  <div class=" col-md-12 " style="margin: 20px auto;">
    <div class="col-md-2 col-md-offset-3">
        <%= image_tag("ajax-loader.gif", :id => "loading-indicator") %>
    </div>

    <div id="display" class="col-md-12" style="margin-top: 20px;">
      <%= render 'content' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>